// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf7TL9jIs0jxPPfqzsRm92fSNjdjqRXzY',
    appId: '1:623722078094:web:c7a513068616fc910acedf',
    messagingSenderId: '623722078094',
    projectId: 'video-2590f',
    authDomain: 'video-2590f.firebaseapp.com',
    storageBucket: 'video-2590f.firebasestorage.app',
    measurementId: 'G-RTE38Q8KQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYeAfEmo-EkGAlFBBB3dNXh58_7QVgo_g',
    appId: '1:623722078094:android:3ade349c034e97fc0acedf',
    messagingSenderId: '623722078094',
    projectId: 'video-2590f',
    storageBucket: 'video-2590f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuND_xPtGbs5T8veTYqX8_NPgNmSZRuf4',
    appId: '1:623722078094:ios:8bc9548f88f8a5350acedf',
    messagingSenderId: '623722078094',
    projectId: 'video-2590f',
    storageBucket: 'video-2590f.firebasestorage.app',
    iosBundleId: 'com.example.videoVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuND_xPtGbs5T8veTYqX8_NPgNmSZRuf4',
    appId: '1:623722078094:ios:8bc9548f88f8a5350acedf',
    messagingSenderId: '623722078094',
    projectId: 'video-2590f',
    storageBucket: 'video-2590f.firebasestorage.app',
    iosBundleId: 'com.example.videoVideo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf7TL9jIs0jxPPfqzsRm92fSNjdjqRXzY',
    appId: '1:623722078094:web:4d735fec7195666c0acedf',
    messagingSenderId: '623722078094',
    projectId: 'video-2590f',
    authDomain: 'video-2590f.firebaseapp.com',
    storageBucket: 'video-2590f.firebasestorage.app',
    measurementId: 'G-7NBHD0FD3D',
  );
}
